### ISSUE TITLE
P2: Reconcile AuthorizationV1 auth_id with legacy authorization_id alias

### ISSUE THREAD

**Issue by AngeYobo** [oxdeai/oxdeai#186]
## Summary

`bench/cases/evaluate.ts` accesses:

```ts
result.authorization.authorization_id
```

However, `PolicyEngine.evaluatePure()` exposes the ALLOW authorization as `AuthorizationV1`, whose normative identifier field is:

```ts
auth_id
```

`AuthorizationV1` does not declare the legacy alias:

```ts
authorization_id
```

The runtime authorization object currently appears to carry both fields through the broader `Authorization = AuthorizationLegacy & AuthorizationV1` construction, but the compile-time type at this call site is the narrower `AuthorizationV1`.

## Observed error

```text
Property 'authorization_id' does not exist on type 'AuthorizationV1'. ts(2339)
```

## Background

This mismatch was discovered during the implementation of trusted-time integration (#184).

The investigation indicates that this is a pre-existing type/runtime inconsistency rather than a regression introduced by #184.

No fix was applied in #184 to keep the trusted-time change focused and avoid expanding its scope.

## Impact

- Benchmark code relies on a legacy runtime alias not represented by the public TypeScript contract.
- Runtime behavior and compile-time types are inconsistent.
- Future cleanup of legacy authorization fields could silently break benchmark code.
- The canonical public authorization identifier is currently ambiguous.

## Decision required

This issue must explicitly determine which identifier is the supported public contract.

### Option A : Migrate callers to `auth_id` (preferred)

Treat `auth_id` as the canonical identifier and migrate benchmark and any remaining internal callers away from `authorization_id`.

This is the preferred direction if `authorization_id` is only a compatibility alias and is **not** part of the supported public API.

### Option B : Widen the public authorization type

Change the relevant engine return type so that `authorization_id` is formally declared alongside `auth_id`.

This is only appropriate if the legacy alias is intentionally part of the public compatibility contract.

### Option C : Deprecate then remove the alias

Document `authorization_id` as deprecated, migrate all internal callers to `auth_id`, and remove the alias in a later semver-major release.

## Questions to resolve

1. Is `authorization_id` part of the supported public API?
2. Is it only a runtime compatibility alias?
3. Should all internal code migrate to `auth_id`?
4. Are there additional call sites still relying on `authorization_id`?
5. Should the public return type of `evaluatePure()` change?

## Recommended direction

Unless repository specifications, published API documentation, or compatibility guarantees explicitly require `authorization_id`, the preferred resolution is:

- keep `AuthorizationV1` as the normative public type;
- migrate benchmark and remaining internal callers to `auth_id`;
- avoid widening `evaluatePure()` to a legacy combined type solely to satisfy benchmark code.

A public API should not be broadened merely to preserve an internal legacy alias.

## Acceptance criteria

- Determine whether `authorization_id` is an intentional public compatibility field or only a legacy runtime alias.
- Document the canonical public authorization identifier.
- Migrate all affected internal callers to the selected contract.
- Align runtime behavior and TypeScript types.
- Add a compile-time regression test.
- Update API documentation if the public type changes.
- Avoid changing authorization hashes, signatures, canonicalization, serialization, or wire format.
- Explicitly classify the change as semver-patch, semver-minor, or semver-major.

## Scope

This issue is intentionally separate from #184.

No trusted-time behavior, replay logic, velocity logic, authorization issuance, canonicalization, or security semantics should change as part of this work.

**Comment by Whatsonyourmind** [comment]
Investigated the call sites and the audit history before touching anything, since this decides a public-contract question. Findings map cleanly onto your five questions, and they land on **Option A** — but with one scoping subtlety that matters, because `authorization_id` turns out to be **overloaded across three distinct roles**, and a naive "migrate everything" would break two of them.

## The three roles of `authorization_id`

1. **Legacy identifier on the authorization *artifact*** — `AuthorizationLegacy.authorization_id` (`packages/core/src/types/authorization.ts:27`), carried at runtime only via `Authorization = AuthorizationLegacy & AuthorizationV1` (`:41`). The normative identifier on `AuthorizationV1` is `auth_id` (`:5`). **This is the actual bug**: `evaluatePure()`'s public output type is the narrow `AuthorizationV1`, so `out.authorization.authorization_id` is `ts(2339)` even though the runtime object still carries the field.
2. **A protocol *reference/record* field** — audit events (`schemas/audit-event.schema.json:37` requires it; `src/audit/AuditLog.ts:23`), intent `RELEASE` (`schemas/intent.schema.json:54` requires it — a RELEASE references the auth being released), and the conformance vectors + canonicalization field lists (`src/crypto/hashes.ts:19`, `packages/conformance/src/validate.ts`, `vectors/*.json`). Here `authorization_id` is *not* the artifact's own identifier — it names a field that *points at* an authorization. These are real protocol surface and fall inside your "do not change canonicalization / serialization / wire format" scope.
3. **An output payload *key*** in CLI/examples — e.g. `packages/cli/src/main.ts:899,1027` and `examples/openai-tools/src/run-openai.ts:185` already emit a key literally named `authorization_id` **whose value is sourced from `auth_id`** (`... authorization_id: outEval.authorization.auth_id`). Renaming those keys is a separate CLI/output-contract decision (semver-minor at least), independent of the `ts(2339)` fix.

## Answering the questions

1. **Is `authorization_id` part of the supported public API?** For the *authorization artifact*: **no**. #102 / #103 (P0-4) narrowed `evaluatePure().authorization` to clean `AuthorizationV1` and made `toPublicAuthorizationV1()` **strip** `authorization_id` (with `engine_signature`, `state_snapshot_hash`, `policy_version`, `expires_at`) from every public signing/hashing surface (`docs/audits/protocol-audit-post-interoperability.md:37,458`). As a *record/reference* field (role 2) it remains real, but that is a different thing from the artifact's identifier.
2. **Only a runtime compatibility alias?** On the artifact — yes: `AuthorizationLegacy` is the "backward-compatible … carries legacy v1.0.x fields" shape, deliberately excluded from the public `AuthorizationV1` boundary.
3. **Should all internal code migrate to `auth_id`?** Only the **role-1 artifact-identifier reads**. Roles 2 and 3 must stay `authorization_id`.
4. **Additional call sites relying on it?** The artifact-identifier reads to migrate: `bench/cases/evaluate.ts:41`, `examples/gpu-guard/demo.mjs:58` (same `out.authorization.authorization_id` read; `.mjs` so no compile error, same conceptual bug), `packages/core/README.md:510` (doc example), and the stale comment at `examples/delegation-demo/src/scenario.ts:64`. Everything else in the grep is role 2 or role 3 and should be left alone. (`packages/cli/src/main.ts:690,853` already fail over correctly with `(auth as any).authorization_id ?? auth.auth_id`.)
5. **Should `evaluatePure()`'s return type change?** **No — and this is the decisive point against Option B.** Widening the return type to re-declare `authorization_id` (Option B) would *reverse* the P0-4 public-artifact-boundary fix: it re-leaks into the public type exactly the field #102/#103 removed. So Option B isn't merely "only appropriate if…"; it's ruled out on audit-consistency grounds unless you intend to undo P0-4.

## Recommendation

**Option A, scoped to role 1 only**, and I agree with your lean — keep `AuthorizationV1` / `auth_id` as the sole canonical public identifier:

- migrate the four artifact-identifier reads above from `.authorization.authorization_id` → `.authorization.auth_id`;
- add a compile-time regression test asserting the ALLOW output of `evaluatePure()` exposes `auth_id` and does **not** structurally expose `authorization_id` (pins the P0-4 boundary so a future widen is caught);
- **do not touch** roles 2 and 3 — audit/RELEASE/vector fields and CLI/example output keys stay as-is (their value already flows from `auth_id`);
- classify **semver-patch**: the public `AuthorizationV1` already excludes `authorization_id`, so no public consumer observes a change; this only aligns internal/bench/example/doc reads with the type that's actually public.

Renaming the role-3 output keys, if you ever want it, is a separate semver-minor issue I'd keep out of this one.

If that scoping matches your intent, I'm happy to open it as the focused PR (four call-site migrations + the compile-time boundary test, nothing in the wire/canonicalization or CLI-output surface) — same discipline as #185. Just confirm role-1-only + patch and I'll ship it.

Refs #184.

**Comment by AngeYobo** [comment]
Hi & Thanks Luka, this is exactly the level of analysis I was hoping for.

I agree with the role split. The important distinction is that the artifact identifier and protocol reference fields are different concepts, even though they currently share the same name.

Let's proceed with **Option A**, scoped strictly to **role 1** (artifact identifier reads).

So the PR should:

* migrate the identified artifact-identifier reads from `authorization.authorization_id` to `authorization.auth_id`;
* add the compile-time regression test protecting the `AuthorizationV1` boundary;
* leave protocol reference fields (`authorization_id` in RELEASE, audit events, vectors, canonicalization, etc.) unchanged;
* leave CLI/output payload keys unchanged.

No wire-format, canonicalization, serialization, or API expansion.

I agree this is a **patch-level internal consistency fix** rather than a protocol change.
